INSERT INTO "S0016140232"."Tdataloader.model::dqg.C_DATA_MAPPING" VALUES(
	'RS_DEK_FILE'/*SOURCE_SYSTEM_ID <NVARCHAR(40)>*/,
	'FIRSTNAME'/*EXTERNAL_FIELD <NVARCHAR(80)>*/,
	''/*OBJECT_ID <NVARCHAR(40)>*/,
	'1:1'/*MATCH_METHOD <NVARCHAR(100)>*/,
	'F0001'/*FIELD_ID_REF <NVARCHAR(20)>*/
);


INSERT INTO "S0016140232"."test.dek.dataloader.model::dqg.C_DATA_MAPPING" VALUES(
	'RS_DEK_FILE'/*SOURCE_SYSTEM_ID <NVARCHAR(40)>*/,
	'LASTNAME'/*EXTERNAL_FIELD <NVARCHAR(80)>*/,
	''/*OBJECT_ID <NVARCHAR(40)>*/,
	'1:1'/*MATCH_METHOD <NVARCHAR(100)>*/,
	'F0002'/*FIELD_ID_REF <NVARCHAR(20)>*/
);


INSERT INTO "S0016140232"."test.dek.dataloader.model::dqg.C_DATA_MAPPING" VALUES(
	'RS_DEK_FILE'/*SOURCE_SYSTEM_ID <NVARCHAR(40)>*/,
	'USER_ID'/*EXTERNAL_FIELD <NVARCHAR(80)>*/,
	'F0004'/*OBJECT_ID <NVARCHAR(40)>*/,
	'1:1'/*MATCH_METHOD <NVARCHAR(100)>*/,
	'F0004'/*FIELD_ID_REF <NVARCHAR(20)>*/
);



INSERT INTO "S0016140232"."test.dek.dataloader.model::dqg.C_DATA_MAPPING" VALUES(
	'RS_DEK_FILE'/*SOURCE_SYSTEM_ID <NVARCHAR(40)>*/,
	'TMP'/*EXTERNAL_FIELD <NVARCHAR(80)>*/,
	'TEMP'/*OBJECT_ID <NVARCHAR(40)>*/,
	'1:1'/*MATCH_METHOD <NVARCHAR(100)>*/,
	'F9999'/*FIELD_ID_REF <NVARCHAR(20)>*/
);


INSERT INTO "S0016140232"."test.dek.dataloader.model::dqg.C_DATA_MAPPING" VALUES(
	'RS_DEK_FILE'/*SOURCE_SYSTEM_ID <NVARCHAR(40)>*/,
	'TMP1'/*EXTERNAL_FIELD <NVARCHAR(80)>*/,
	'TEMP2'/*OBJECT_ID <NVARCHAR(40)>*/,
	'1:1'/*MATCH_METHOD <NVARCHAR(100)>*/,
	'F888'/*FIELD_ID_REF <NVARCHAR(20)>*/
);