CREATE COLUMN TABLE "S0016140232"."DQG_MASTER_DATA"(
	"OBJECT_ID" NVarCHAR(40) NOT NULL,
	"SOURCE_SYSTEM_ID" NVarCHAR(40) NOT NULL,
	"FIELD_ID_REF" NVARCHAR(20) not null,
	"START_DATE" date,
	"END_DATE" date,
	"FIELD_TYPE" nvarchar(20),
	"VALUE" nvarchar(80),
	"CHANGED" boolean,
	
	PRIMARY KEY (
		"OBJECT_ID",
		"SOURCE_SYSTEM_ID",
		"FIELD_ID_REF",
		"START_DATE"
	),
	FOREIGN KEY (FIELD_ID_REF) REFERENCES DQG_FIELDS(FIELD_ID)
)
