CREATE COLUMN TABLE "S0016140232"."DQG_DATA_MAPPING" (
    "SOURCE_SYSTEM_ID" NVARCHAR(40) NOT NULL , 
    "EXTERNAL_FIELD" NVARCHAR(80) NOT NULL , 
    "OBJECT_ID" NVARCHAR(40), 
    "MATCH_METHOD" NVARCHAR(100), 
    "FIELD_ID_REF" NVARCHAR(20), 
    
    PRIMARY KEY (
        "SOURCE_SYSTEM_ID", 
        "EXTERNAL_FIELD"
    ),
    
    FOREIGN KEY ( "FIELD_ID_REF" ) REFERENCES "S0016140232"."DQG_FIELDS" ("FIELD_ID")
)
