CREATE COLUMN TABLE "S0016140232"."DQG_FIELDS" (
    "FIELD_ID" NVARCHAR(20) NOT NULL , 
    "LABEL" NVARCHAR(40), 
    "DESCRIPTION" NVARCHAR(100), 
    "FIELD_TYPE" NVARCHAR(20), 
    "PRUGE_FLAG" BOOLEAN,
    
    PRIMARY KEY ("FIELD_ID")
);
